debug
Signed-off-by: Maksim Fedotov <maksim.fedotov@flant.com>

diff --git a/images/packages/libunistring/werf.inc.yaml b/images/packages/libunistring/werf.inc.yaml
--- a/images/packages/libunistring/werf.inc.yaml
+++ b/images/packages/libunistring/werf.inc.yaml
@@ -30,11 +30,12 @@ shell:
   - |
     git clone --depth=1 $(cat /run/secrets/SOURCE_REPO)/{{ $gitRepoUrl }} --branch {{ $version }} /src
     cd /src
-    for p in /patches/*.patch ; do
-      echo -n "Apply ${p} ... "
-      git apply --ignore-space-change --ignore-whitespace ${p} && echo OK || (echo FAIL ; exit 1)
-    done
+    # for p in /patches/*.patch ; do
+    #   echo -n "Apply ${p} ... "
+    #   git apply --ignore-space-change --ignore-whitespace ${p} && echo OK || (echo FAIL ; exit 1)
+    # done
     git clone $(cat /run/secrets/SOURCE_REPO)/gnulib.git ./gnulib
+    # git checkout c89cd2fbd3b9f3d7c5a146247256599714c91ec7
 
 ---
 
@@ -73,8 +74,9 @@ shell:
   - |
     OUTDIR=/out
     cd /src
+    export GNULIB_SRCDIR=$(pwd)/gnulib
     export GNULIB_TOOL=$(pwd)/gnulib/gnulib-tool
-    ./autogen.sh --skip-gnulib
+    ./autogen.sh
     ./configure \
       --prefix=/usr \
       --libdir=/usr/lib64
