change edk2 build,rm alt build libvirt,qemu
Signed-off-by: Nikita Korolev <nikita.korolev@flant.com>

diff --git a/images/qemu/werf.inc.yaml b/images/qemu/werf.inc.yaml
--- a/images/qemu/werf.inc.yaml
+++ b/images/qemu/werf.inc.yaml
@@ -3,328 +3,6 @@
 {{- $version := get $.Version $gitRepoName }}
 {{- $gitRepoUrl := cat $.SOURCE_REPO "/qemu/qemu.git" | nospace }}
 
-{{/*
-
-# image: {{ $.ImageName }}-alt
-# final: false
-# fromImage: base-alt-p11
-# git:
-# - add: /images/{{ $.ImageName }}/
-#   to: /
-#   includePaths:
-#   - install-qemu.sh
-#   - patches
-#   excludePaths:
-#     - patches/README.md
-#   stageDependencies:
-#     setup:
-#       - install-qemu.sh
-# shell:
-#   beforeInstall:
-#   - |
-#     apt-get update && apt-get install -y \
-#     binutils \
-#     pkgconfig \
-#     pkg-config \
-#     dmidecode \
-#     gcc-c++ \
-#     git \
-#     gettext \
-#     bash-completion \
-#     clang \
-#     ccache \
-#     make cmake \
-#     meson \
-#     ninja-build \
-#     glibc-devel-static \
-#     zlib-devel-static \
-#     glib2-devel-static \
-#     libpcre2-devel-static \
-#     libattr-devel-static \
-#     libdw-devel-static \
-#     libatomic-devel-static \
-#     glib2-devel \
-#     libdw-devel \
-#     makeinfo \
-#     perl-devel \
-#     python3 python3-dev \
-#     python3-module-pytest \
-#     python3-module-docutils \
-#     python3-tools \
-#     python3-module-pip \
-#     python3-module-sphinx \
-#     python3-module-sphinx_rtd_theme \
-#     pkgconfig \
-#     libssh-devel \
-#     libssh2-devel \
-#     libcap-ng-devel \
-#     libxfs-devel \
-#     zlib-devel \
-#     libcurl-devel \
-#     libpci-devel \
-#     libgvnc-devel \
-#     glibc-kernheaders \
-#     ipxe-roms-qemu \
-#     seavgabios \
-#     seabios \
-#     libfdt-devel \
-#     qboot \
-#     libpixman-devel \
-#     libkeyutils-devel \
-#     flex \
-#     libuuid-devel \
-#     libpam0-devel \
-#     libtasn1-devel \
-#     libslirp-devel \
-#     libdrm-devel \
-#     libxdp-devel libSDL2-devel libSDL2_image-devel \
-#     libncursesw-devel libalsa-devel libpulseaudio-devel \
-#     pipewire-libs pipewire-jack-libs-devel \
-#     libsoundio-devel libcapstone-devel libsasl2-devel \
-#     libjpeg-devel libpng-devel libxkbcommon-devel xkeyboard-config-devel \
-#     glusterfs11 libgtk+3-devel libvte libvte-devel libvte3-devel \
-#     libvirglrenderer-devel libusb-devel liburing-devel libbpf-devel \
-#     libspice-server-devel spice-protocol ceph-devel \
-#     libnfs-devel libzstd-devel libseccomp-devel \
-#     libgcrypt-devel libgnutls-devel libnettle-devel \
-#     libudev-devel libmultipath-devel libblkio-devel libpmem-devel \
-#     libdaxctl-devel libfuse3-devel rdma-core-devel libnuma-devel \
-#     bzlib-devel liblzo2-devel libsnappy-devel \
-#     libcacard-devel libusbredir-devel libepoxy-devel libgbm-devel \
-#     libvitastor-devel libiscsi-devel glusterfs-coreutils \
-#     libaio-devel libselinux-devel libqpl-devel \
-#     qemu-kvm-core shadow-utils sysvinit-utils libglusterfs11-api-devel hasher-provides-dev-kvm \
-#     filesystem libvdeplug-devel
-
-#     apt-get clean
-#     rm --recursive --force /var/lib/apt/lists/ftp.altlinux.org* /var/cache/apt/*.bin
-#     rm -f /usr/lib*/python3*/EXTERNALLY-MANAGED
-#     rpm -qa | sort > /packages.txt
-
-#     mkdir -p /usr/libexec/ccache-wrappers
-#     ln -s /usr/bin/ccache /usr/libexec/ccache-wrappers/cc
-#     ln -s /usr/bin/ccache /usr/libexec/ccache-wrappers/clang
-#     ln -s /usr/bin/ccache /usr/libexec/ccache-wrappers/gcc
-
-#     pip3 install black
-
-#   install:
-#   - |
-#     export CCACHE_WRAPPERSDIR="/usr/libexec/ccache-wrappers"
-#     export CCACHE_DIR="$CCACHE_BASEDIR/ccache"
-#     export CCACHE_BASEDIR="$(pwd)"
-#     export PATH="$CCACHE_WRAPPERSDIR:$PATH"
-#     export MAKE="/usr/bin/make"
-#     export NINJA="/usr/bin/ninja"
-#     export PYTHON="/usr/bin/python3"
-
-#     git clone --depth=1 --branch v{{ $version }} {{ $gitRepoUrl }} {{ $gitRepoName }}-{{ $version }}
-
-#     cd {{ $gitRepoName }}-{{ $version }}
-
-#     for p in /patches/*.patch ; do
-#       echo -n "Apply ${p} ... "
-#       git apply  --ignore-space-change --ignore-whitespace ${p} && echo OK || (echo FAIL ; exit 1)
-#     done
-
-#     ./configure \
-#       --target-list="x86_64-softmmu" \
-#       --with-pkgversion="-dvp" \
-#       --with-coroutine=ucontext \
-#       --tls-priority="@QEMU,SYSTEM" \
-#       --block-drv-rw-whitelist="qcow2,raw,file,host_device,nbd,iscsi,rbd,blkdebug,luks,null-co,nvme,copy-on-read,throttle,compress,virtio-blk-vhost-vdpa,virtio-blk-vfio-pci,virtio-blk-vhost-user,io_uring,nvme-io_uring" \
-#       --block-drv-ro-whitelist="vdi,vmdk,vhdx,vpc,https" \
-#       --disable-alsa                   \
-#       --disable-attr                   \
-#       --disable-auth-pam               \
-#       --disable-avx2                   \
-#       --disable-avx512bw               \
-#       --disable-blkio                  \
-#       --disable-block-drv-whitelist-in-tools \
-#       --disable-bochs                  \
-#       --disable-bpf                    \
-#       --disable-brlapi                 \
-#       --disable-bsd-user               \
-#       --disable-bzip2                  \
-#       --disable-cap-ng                 \
-#       --disable-capstone               \
-#       --disable-cfi                    \
-#       --disable-cfi-debug              \
-#       --disable-cloop                  \
-#       --disable-cocoa                  \
-#       --disable-coreaudio              \
-#       --disable-coroutine-pool         \
-#       --disable-crypto-afalg           \
-#       --disable-curl                   \
-#       --disable-curses                 \
-#       --disable-dbus-display           \
-#       --disable-debug-info             \
-#       --disable-debug-mutex            \
-#       --disable-debug-tcg              \
-#       --disable-dmg                    \
-#       --disable-docs                   \
-#       --disable-dsound                 \
-#       --disable-fdt                    \
-#       --disable-fuse                   \
-#       --disable-fuse-lseek             \
-#       --disable-gcrypt                 \
-#       --disable-gettext                \
-#       --disable-gio                    \
-#       --disable-glusterfs              \
-#       --disable-gnutls                 \
-#       --disable-gtk                    \
-#       --disable-guest-agent            \
-#       --disable-guest-agent-msi        \
-#       --disable-hvf                    \
-#       --disable-iconv                  \
-#       --disable-jack                   \
-#       --disable-kvm                    \
-#       --disable-l2tpv3                 \
-#       --disable-libdaxctl              \
-#       --disable-libdw                  \
-#       --disable-libiscsi               \
-#       --disable-libnfs                 \
-#       --disable-libpmem                \
-#       --disable-libssh                 \
-#       --disable-libudev                \
-#       --disable-libusb                 \
-#       --disable-libvduse               \
-#       --disable-linux-aio              \
-#       --disable-linux-io-uring         \
-#       --disable-linux-user             \
-#       --disable-lto                    \
-#       --disable-lzfse                  \
-#       --disable-lzo                    \
-#       --disable-malloc-trim            \
-#       --disable-membarrier             \
-#       --disable-modules                \
-#       --disable-module-upgrades        \
-#       --disable-mpath                  \
-#       --disable-multiprocess           \
-#       --disable-netmap                 \
-#       --disable-nettle                 \
-#       --disable-numa                   \
-#       --disable-nvmm                   \
-#       --disable-opengl                 \
-#       --disable-oss                    \
-#       --disable-pa                     \
-#       --disable-parallels              \
-#       --disable-pie                    \
-#       --disable-plugins                \
-#       --disable-qcow1                  \
-#       --disable-qed                    \
-#       --disable-qga-vss                \
-#       --disable-qom-cast-debug         \
-#       --disable-rbd                    \
-#       --disable-rdma                   \
-#       --disable-replication            \
-#       --disable-rng-none               \
-#       --disable-safe-stack             \
-#       --disable-sdl                    \
-#       --disable-sdl-image              \
-#       --disable-seccomp                \
-#       --disable-selinux                \
-#       --disable-slirp                  \
-#       --disable-slirp-smbd             \
-#       --disable-smartcard              \
-#       --disable-snappy                 \
-#       --disable-sndio                  \
-#       --disable-sparse                 \
-#       --disable-spice                  \
-#       --disable-spice-protocol         \
-#       --disable-strip                  \
-#       --disable-system                 \
-#       --disable-tcg                    \
-#       --disable-tools                  \
-#       --disable-tpm                    \
-#       --disable-u2f                    \
-#       --disable-usb-redir              \
-#       --disable-user                   \
-#       --disable-vde                    \
-#       --disable-vdi                    \
-#       --disable-vduse-blk-export       \
-#       --disable-vhost-crypto           \
-#       --disable-vhost-kernel           \
-#       --disable-vhost-net              \
-#       --disable-vhost-user             \
-#       --disable-vhost-user-blk-server  \
-#       --disable-vhost-vdpa             \
-#       --disable-virglrenderer          \
-#       --disable-virtfs                 \
-#       --disable-vnc                    \
-#       --disable-vnc-jpeg               \
-#       --disable-png                    \
-#       --disable-vnc-sasl               \
-#       --disable-vte                    \
-#       --disable-vvfat                  \
-#       --disable-werror                 \
-#       --disable-whpx                   \
-#       --disable-xen                    \
-#       --disable-xen-pci-passthrough    \
-#       --disable-xkbcommon              \
-#       --disable-zstd                   \
-#       --enable-attr                    \
-#       --enable-blkio                   \
-#       --enable-cap-ng                  \
-#       --enable-capstone                \
-#       --enable-coroutine-pool          \
-#       --enable-curl                    \
-#       --enable-dbus-display            \
-#       --enable-debug-info              \
-#       --enable-fdt=system              \
-#       --enable-gio                     \
-#       --enable-gnutls                  \
-#       --enable-guest-agent             \
-#       --enable-iconv                   \
-#       --enable-kvm                     \
-#       --enable-libusb                  \
-#       --enable-libudev                 \
-#       --enable-linux-aio               \
-#       --enable-linux-io-uring          \
-#       --enable-lzo                     \
-#       --enable-malloc-trim             \
-#       --enable-modules                 \
-#       --enable-mpath                   \
-#       --enable-numa                    \
-#       --enable-opengl                  \
-#       --enable-pa                      \
-#       --enable-pie                     \
-#       --enable-rbd                     \
-#       --enable-rdma                    \
-#       --enable-seccomp                 \
-#       --enable-selinux                 \
-#       --enable-slirp                   \
-#       --enable-snappy                  \
-#       --enable-spice-protocol          \
-#       --enable-system                  \
-#       --enable-tcg                     \
-#       --enable-tools                   \
-#       --enable-tpm                     \
-#       --enable-usb-redir               \
-#       --enable-vdi                     \
-#       --enable-vhost-kernel            \
-#       --enable-vhost-net               \
-#       --enable-vhost-user              \
-#       --enable-vhost-user-blk-server   \
-#       --enable-vhost-vdpa              \
-#       --enable-vnc                     \
-#       --enable-png                     \
-#       --enable-vnc-sasl                \
-#       --enable-werror                  \
-#       --enable-xkbcommon               \
-#       --enable-zstd
-
-#       make -j$(nproc)
-
-#   setup:
-#   - |
-#     /install-qemu.sh --version-num "{{ $version }}" \
-#                         -s /{{ $gitRepoName }}-{{ $version }} \
-#                         -d /BINS \
-#                         -b build
-# ---
-*/}}
-
 image: {{ $.ImageName }}
 final: false
 from: {{ .Images.BASE_DEBIAN_BOOKWORM_SLIM }}
@@ -418,6 +96,7 @@ shell:
                       libncursesw5-dev \
                       libnfs-dev \
                       libnuma-dev \
+                      libibumad-dev \
                       libpam0g-dev \
                       libpcre2-dev \
                       libpipewire-0.3-dev \
@@ -530,10 +209,10 @@ shell:
 
     cd {{ $gitRepoName }}-{{ $version }}
 
-    for p in /patches/*.patch ; do
-      echo -n "Apply ${p} ... "
-      git apply  --ignore-space-change --ignore-whitespace ${p} && echo OK || (echo FAIL ; exit 1)
-    done
+    # for p in /patches/*.patch ; do
+    #   echo -n "Apply ${p} ... "
+    #   git apply  --ignore-space-change --ignore-whitespace ${p} && echo OK || (echo FAIL ; exit 1)
+    # done
 
     ./configure \
       --target-list="x86_64-softmmu" \
