add deckhouse_ready_status check
Signed-off-by: Maksim Fedotov <maksim.fedotov@flant.com>

diff --git a/tests/e2e/Taskfile.yaml b/tests/e2e/Taskfile.yaml
--- a/tests/e2e/Taskfile.yaml
+++ b/tests/e2e/Taskfile.yaml
@@ -148,6 +148,11 @@ tasks:
           echo "Error: v12n_tag is not set."
           exit 1
         fi
+        DECKHOUSE_READY_STATUS=$(kubectl get po -n d8-system -l app=deckhouse -o json | jq -r '.items[0].status.conditions[] | select(.type=="ContainersReady") | .status')
+        if [ "$DECKHOUSE_READY_STATUS" != "True" ]; then
+          echo "Error: Deckhouse is not ready."
+          exit 1
+        fi
         d8 k patch mpo virtualization --type merge -p "{\"spec\":{\"imageTag\":\"$v12n_tag\"}}" 
         images_hash=$(crane export "dev-registry.deckhouse.io/sys/deckhouse-oss/modules/virtualization:$v12n_tag" - | tar -Oxf - images_digests.json)
         v12n_pods=$(kubectl -n d8-virtualization get pods -o json | jq -c)
