use task for check version in registry
Signed-off-by: Nikita Korolev <nikita.korolev@flant.com>

diff --git a/tools/moduleversions/Taskfile.dist.yaml b/tools/moduleversions/Taskfile.dist.yaml
--- a/tools/moduleversions/Taskfile.dist.yaml
+++ b/tools/moduleversions/Taskfile.dist.yaml
@@ -30,6 +30,34 @@ tasks:
     cmds:
       - go run ./main.go moduleversions --channel {{.CHANNEL}} --version {{.VERSION}} --attempt {{.COUNT}} --check-docs
 
+  check:registry:
+    desc: "Check version in the registry"
+    vars:
+      VERSION: "{{ .VERSION }}"
+      CHANNEL: "{{ .CHANNEL }}"
+    cmds:
+      - |
+        if [[ -z "{{ .VERSION }}" ]] && [[ -z "{{ .CHANNEL }}" ]]; then
+          echo "TAG and CHANNEL are required"
+          exit 1
+        fi
+
+        EDITIONS=("ee" "fe" "ce" "se-plus")
+        PROD_REGISTRY="registry.deckhouse.io/deckhouse"
+
+        for EDITION in ${EDITIONS[@]}; do
+          echo "Check version on $EDITION"
+          getVersion=$(crane export "$PROD_REGISTRY/$EDITION/modules/virtualization/release:{{ .CHANNEL }}" - | tar -Oxf - version.json | jq '.version' -r)
+          
+          if [[ "$getVersion" != "{{ .VERSION }}" ]]; then
+            echo "Version is not valid in $EDITION and channel {{ .CHANNEL }}"
+            echo "Expected version: {{ .VERSION }} but got $getVersion"
+            exit 1
+          else
+            echo "Version {{ .VERSION }} is valid in $EDITION and channel {{ .CHANNEL }}"
+          fi
+        done
+
   crane:version:
     desc: "Get version from release image"
     vars:
