add dbg
Signed-off-by: Nikita Korolev <nikita.korolev@flant.com>

diff --git a/.github/workflows/dev_module_build.yml b/.github/workflows/dev_module_build.yml
--- a/.github/workflows/dev_module_build.yml
+++ b/.github/workflows/dev_module_build.yml
@@ -202,14 +202,16 @@ jobs:
 
           for dir in "${config_dirs[@]}"; do
             # echo "::group::📂 Linting directory: $dir"
-            # cd "$dir" || { echo "::error::Failed to access directory $dir"; exit 1; }
 
             cd "$dir" || { echo "::error::Failed to access directory $dir"; continue; }
             
             # Run linter with multiple formats
             
-            output=$(golangci-lint run --sort-results --out-format=json | jq '.Issues[] | {linter: .FromLinter, rule: .Text, lines: .SourceLines, file: "\(.Pos.Filename):\(.Pos.Line):\(.Pos.Column)"}' || true)
-            find_errors=$(echo $output | wc -l)
+            output=$(golangci-lint run --sort-results --out-format=json | jq '.Issues[] | {linter: .FromLinter, rule: .Text, lines: .SourceLines, file: "\(.Pos.Filename):\(.Pos.Line):\(.Pos.Column)"}')
+            find_errors=$(echo $output | jq '. | select(.!=null)' | wc -l)
+
+            echo "after output"
+            echo "$? exit code"
             
             # Track errors
             if [ $find_errors -ne 0 ]; then
@@ -244,6 +246,7 @@ jobs:
           echo "has_errors=$has_errors" >> "$GITHUB_OUTPUT"
 
           if [ $error_count -gt 0 ]; then
+            echo "$error_count error more than 0, exit 1"
             exit 1
           fi
 
