refactor(ci): switch from merge commit to head sha commit in builds (#446)
Switch from Merge commit to HEAD SHA to prevent rebuilding images that have not been modified in the current branch
---------

Signed-off-by: Nikita Korolev <nikita.korolev@flant.com>
Co-authored-by: Ivan Mikheykin <ivan.mikheykin@flant.com>

diff --git a/.github/workflows/dev_module_build.yml b/.github/workflows/dev_module_build.yml
--- a/.github/workflows/dev_module_build.yml
+++ b/.github/workflows/dev_module_build.yml
@@ -26,8 +26,12 @@ env:
 
 on:
   workflow_dispatch:
+    inputs:
+      pr_number:
+        required: false
+        type: number
   pull_request:
-    types: [opened, synchronize]
+    types: [opened, reopened, synchronize]
   push:
     branches:
       - main
@@ -53,8 +57,14 @@ jobs:
         run: |
           if [[ "${{ github.ref_name }}" == 'pre-alpha' || "${{ github.ref_name }}" == 'main' ]]; then
             MODULES_MODULE_TAG="${{ github.ref_name }}"
-          else
+          elif [[ -n "${{ github.event.pull_request.number }}" ]]; then
             MODULES_MODULE_TAG="pr${{ github.event.pull_request.number }}"
+          elif [[ -n "${{ github.event.inputs.pr_number }}" ]]; then
+            MODULES_MODULE_TAG="pr${{ github.event.inputs.pr_number }}"
+          else
+            echo "Cannot set MODULES_MODULE_TAG variable"
+            echo "Exit"
+            exit 1
           fi
 
           echo "MODULES_MODULE_TAG=$MODULES_MODULE_TAG" >> "$GITHUB_OUTPUT"
@@ -121,6 +131,8 @@ jobs:
           version: 3.37.2
 
       - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
       - name: Run lint virtualization-controller
         run: |
@@ -138,7 +150,7 @@ jobs:
 
       - uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
       - name: Lint yaml with prettier
         run: task -p lint:prettier:yaml
@@ -158,6 +170,8 @@ jobs:
           version: 3.37.2
 
       - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
       - name: Run test hooks
         run: |
@@ -174,6 +188,7 @@ jobs:
     needs: set_vars
     env:
       MODULES_MODULE_TAG: ${{needs.set_vars.outputs.modules_module_tag}}
+      WERF_VIRTUAL_MERGE: 0
     steps:
       - name: Print vars
         run: |
@@ -186,6 +201,7 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
       - name: Remove unwanted software
         uses: ./.github/actions/remove-unwanted-software
