fix
Signed-off-by: Maksim Fedotov <maksim.fedotov@flant.com>

diff --git a/.github/workflows/dev_module_build.yml b/.github/workflows/dev_module_build.yml
--- a/.github/workflows/dev_module_build.yml
+++ b/.github/workflows/dev_module_build.yml
@@ -428,17 +428,14 @@ jobs:
           trivy_registry_password: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
           deckhouse_private_repo: ${{vars.DECKHOUSE_PRIVATE_REPO}}
       - name: Fail if CVEs were found
-        env:
-          MODULE_NAME: ${{ vars.MODULE_NAME }}
-          IMAGE_NAME: ${{needs.set_vars.outputs.modules_module_tag}}
         run: |
-          ls out/json
-          report=out/json/d8_${MODULE_NAME}_${IMAGE_NAME}_report.json
-          cve_count=$(cat $report | jq '.Results // [] | map(.Vulnerabilities | length) | add // 0')
-          if [[ $cve_count -gt 0 ]]; then
-            echo "::error::CVEs were found in images"
-            exit 1
-          fi
+          for report in out/json/d8_*_report.json; do
+            cve_count=$(cat $report | jq '.Results // [] | map(.Vulnerabilities | length) | add // 0')
+            if [[ $cve_count -gt 0 ]]; then
+              echo "::error::CVEs were found in images"
+              exit 1
+            fi
+          done
 
   skip_e2e:
     if: ${{ github.event.label.name == 'skip/e2e' }}
